# initramfs-tools package

INITRAMFS_TOOLS_VERSION = 0.130
export INITRAMFS_TOOLS_VERSION

BACKUP_PREFIX = https://github.com/nirenjan/arlo-files/blob/master/initramfs-tools

INITRAMFS_TOOLS = initramfs-tools_$(INITRAMFS_TOOLS_VERSION)_all.deb
$(INITRAMFS_TOOLS)_URL = "$(BACKUP_PREFIX)/$(INITRAMFS_TOOLS)?raw=true"
#$(INITRAMFS_TOOLS)_SRC_PATH = $(SRC_PATH)/initramfs-tools
#SONIC_MAKE_DEBS += $(INITRAMFS_TOOLS)

INITRAMFS_TOOLS_CORE = initramfs-tools-core_$(INITRAMFS_TOOLS_VERSION)_all.deb
$(INITRAMFS_TOOLS_CORE)_URL = "$(BACKUP_PREFIX)/$(INITRAMFS_TOOLS_CORE)?raw=true"
#$(eval $(call add_extra_package,$(INITRAMFS_TOOLS),$(INITRAMFS_TOOLS_CORE)))

#SONIC_STRETCH_DEBS += $(INITRAMFS_TOOLS) $(INITRAMFS_TOOLS_CORE)

SONIC_ONLINE_DEBS += $(INITRAMFS_TOOLS) $(INITRAMFS_TOOLS_CORE)
